### ISSUE TITLE
Pedido demorando muito para chegar

### ISSUE THREAD

**Issue by thiagosjk** [thiagosjk/openPizza#10]
Dashboard Pizzarias (Pedidos). O pedido está demorando muito para chegar no painel da pizzaria. No nosso dashboard chega instantaneamente e por e-mail instantaneamente também. Estivemos monitorando e hoje de manhã levou 11 minutos para chegar no dashboard da pizzaria. Existe uma maneira de aparecer mais rápido no dashboard da pizzaria?

**Comment by thiagosjk** [comment]
Pode ser um problema de Cache... Tente desabilitar os plugins de cache

**Comment by anywolf** [comment]
Todos pedidos que fiz chegaram instantaneamente.
