### ISSUE TITLE
Horário painel - UTC

### ISSUE THREAD

**Issue by thiagosjk** [thiagosjk/openPizza#11]
*critico*
Dashboard Pizzarias (Pedidos). O horário que aparece na listagem de pedidos é diferente do que aparece quando abrimos o pedido. Trata-se do fuso horário, o sistema está recebendo o fuso horário de diferentes lugares, no Brasil o  UTC é -3. Entre com o login abaixo e confira: stellas.openpizza@gmail.com senha: stellas1234

**Comment by anywolf** [comment]
/wp-content/plugins/wedevs-dokan-plugin/templates/orders/listings.php

<td class="dokan-order-date">

**Comment by anywolf** [comment]
https://developer.wordpress.org/reference/functions/human_time_diff/

**Comment by anywolf** [comment]
linha 81-82  /wp-content/plugins/wedevs-dokan-plugin/templates/orders/listings.php
Trocar current_time( 'timestamp', 1 ) para  current_time( 'timestamp', 1 )

if ( $time_diff > 0 && $time_diff < 24 * 60 * 60 )
                                $h_time = sprintf( __( '%s ago', 'dokan' ), human_time_diff( $gmt_time, current_time( 'timestamp', 0 ) ) );
