### ISSUE TITLE
Alterar endereço indicando wpEngine

### ISSUE THREAD

**Issue by thiagosjk** [thiagosjk/openPizza#13]
Login: User - Quando clicamos na opção "Editar Endereço" ele direciona para a seguinte página http://mypizza.wpengine.com/my-account/edit-address/  (as vezes ela funciona corretamente)

**Comment by thiagosjk** [comment]
Por via das dúvidas, rodar script no banco substituindo "mypizza.wpengine.com" por "openpizza.com.br" na tabela wp_options

**Comment by thiagosjk** [comment]
Por via das dúvidas, rodar script no banco substituindo "mypizza.wpengine.com" por "openpizza.com.br" na tabela wp_postmeta

**Comment by thiagosjk** [comment]
Por via das dúvidas, rodar script no banco substituindo "mypizza.wpengine.com" por "openpizza.com.br" na tabela wp_posts

**Comment by thiagosjk** [comment]
update TABELA set CAMPO = replace(CAMPO, "mypizza.wpengine.com","openpizza.com.br");

**Comment by anywolf** [comment]
As vezes funciona as vezes não

**Comment by anywolf** [comment]
UPDATE wp_postmeta SET meta_value = replace(meta_value, 'http://mypizza.wpengine.com/my-account/edit-address/', 'http://openpizza.provisorio.ws/my-account/edit-address/') WHERE meta_key = '_menu_item_url';
