### ISSUE TITLE
Avatar da Pizzaria no mapa

### ISSUE THREAD

**Issue by thiagosjk** [thiagosjk/openPizza#14]
Trocar o avatar da pizzaria no mapa

**Comment by anywolf** [comment]
functions.php no tema openpizza

linha 388 

$urlImgStatic = 'http://openpizza.provisorio.ws/wp-content/uploads/2014/10/openpizza-bg-image.jpg';

	$atts[] = sprintf( 'style="background-image: url(%s);"', $urlImgStatic);



Mudar em pizzarias as imagens em destaque
