### ISSUE TITLE
Avaliação de pizzarias

### ISSUE THREAD

**Issue by thiagosjk** [thiagosjk/openPizza#15]
Quando a pizzaria recebe uma avaliação, ela recebe um mensagem no email, mas ela não aparece no dashboard para aprovação. ( no nosso painel aparece normalmente)

**Comment by thiagosjk** [comment]
![16](https://cloud.githubusercontent.com/assets/1133137/12180405/7d7d0ba4-b563-11e5-87cd-ef5cbf44b862.jpg)

**Comment by anywolf** [comment]
No painel da pizzaria não aparece!

**Comment by anywolf** [comment]
wp-content/plugins/wedevs-dokan-plugin/classes/template-reviews.php

**Comment by anywolf** [comment]
teste:
SELECT comment_content, comment_ID, comment_author,
                comment_author_email, comment_author_url,
                user_id, comment_post_ID, comment_approved,
                comment_date
            FROM wp_comments
            WHERE 
                comment_post_ID=2025
                 ORDER BY comment_date DESC   




"SELECT c.comment_content, c.comment_ID, c.comment_author,
                c.comment_author_email, c.comment_author_url,
                p.post_title, c.user_id, c.comment_post_ID, c.comment_approved,
                c.comment_date
            FROM wp_comments as c, wp_posts as p
            WHERE p.post_author='$id' AND
                p.post_status='publish' AND
                c.comment_post_ID=p.ID AND
                comment_approved IN ('1','0')
                p.post_type='$post_type'  ORDER BY c.comment_ID DESC
            LIMIT $offset,$limit"

**Comment by anywolf** [comment]
"SELECT c.comment_content, c.comment_ID, c.comment_author,
                c.comment_author_email, c.comment_author_url,
                c.user_id, c.comment_post_ID, c.comment_approved,
                c.comment_date, p.post_title
                FROM wp_comments c
                INNER JOIN ( 
                  SELECT * from wp_posts where post_author='$id' AND post_status='publish') p
                ON
                c.comment_post_ID=p.ID
                WHERE comment_approved IN ('1','0')
                ORDER BY c.comment_ID DESC
                LIMIT $offset,$limit"
