### ISSUE TITLE
Sugerir instalação do APP em dispositivos móveis

### ISSUE THREAD

**Issue by thiagosjk** [thiagosjk/openPizza#16]
Quando eu acesso o site do Mercado Livre através do celular, uma mensagem aparece sugerindo que eu instale o aplicativo. Seria possível fazer o mesmo no nosso site?

**Comment by anywolf** [comment]
https://wordpress.org/plugins/appbanners/screenshots/
Seria alguma coisa parecida com isso?

**Comment by anywolf** [comment]
Fazer teste no IOS

**Comment by anywolf** [comment]
instalar https://wordpress.org/plugins/appbanners/

IOS id: 1052669969
Android id: com.app.openpizza
