### ISSUE TITLE
Porcentagem no valor da pizza

### ISSUE THREAD

**Issue by thiagosjk** [thiagosjk/openPizza#17]
*critico*
No pluging "TM global extra product options" nós configuramos valores para os tamanhos das pizzas. Existe uma opção para que o valor da pizza média, por exemplo, seja uma porcentagem do valor da grande, porém, essa opção não está funcionando. Quando eu coloco um valor fixo funciona perfeitamente.

**Comment by anywolf** [comment]
Problema com link editar quando atualiza wordpress

em wp-content/plugins/woocommerce-tm-extra-product-options/admin/class-tm-epo-admin-global-list-table.php na linha 710 mudar para:

//função get_edit_post_link não funcionando corretamente, por isso adicionar link direto para conseguir editar os produtos do tm global
					//$actions['edit'] = '<a href="' . get_edit_post_link( $post->ID, true ) . '" title="' . esc_attr( __( 'Edit this item', TM_EPO_TRANSLATION ) ) . '">' . __( 'Edit' , TM_EPO_TRANSLATION) . '</a>';

					$actions['edit'] = '<a href="edit.php?post_type=product&page=tm-global-epo&action=edit&post='.$post->ID.'" title="' . esc_attr( __( 'Edit this item', TM_EPO_TRANSLATION ) ) . '">' . __( 'Edit' , TM_EPO_TRANSLATION) . '</a>';

**Comment by anywolf** [comment]
Atualizar plugin para versão 4.2.3

Configurar em sale a porcentagem.

em wp-content/plugins/woocommerce-tm-extra-product-options/assets/js/tm-epo.js  em switch(pricetype) colocar 
                        case 'biggest':
                        price =  Math.max(price, product_price) > product_price ? price - product_price : 0;
                        break;

em wp-content/plugins/woocommerce-tm-extra-product-options/include/class-tm-extra-product-options.php colocar

                                        case 'biggest':
					if ($cpf_product_price){
						$_price = max($_price, $cpf_product_price) > $cpf_product_price ? $_price - $cpf_product_price : 0;
					}
					break;
