### ISSUE TITLE
Melhorar tela de pedido

### ISSUE THREAD

**Issue by thiagosjk** [thiagosjk/openPizza#18]
*critico*
Cadastro dos Clientes - Precisamos inserir a base de CEP no nosso sistema, para facilitar o cadastro. Hoje os clientes tem que digitar todos os dados. (ver possibilidade de logar com facebook)

Seria ideal que o cara colocasse o CEP dele e depois todos os campos fossem preenchidos automaticamente

**Comment by anywolf** [comment]
Campos ultimo nome e país tirado
E cep autocomplete adicionado

**Comment by thiagosjk** [comment]
Adicionando o plugin WooCommerce Extra Checkout Fields for Brazil e ativando auto-complete de CEP

Alterando o nome do campo BAIRRO para billing_neighborhood

Ocultando os campos LastName e Country no style.css do child-theme

#billing_country_field, #billing_last_name_field{
    display:none;
}

**Comment by thiagosjk** [comment]
Adicionando o plugin WooCommerce Extra Checkout Fields for Brazil e ativando auto-complete de CEP

Alterando o nome do campo BAIRRO para billing_neighborhood

Ocultando os campos LastName e Country no style.css do child-theme

#billing_country_field, #billing_last_name_field{
    display:none;
}

**Comment by pandoapps** [comment]
Desabiiltar tipo de pessoa no woocommerce-extra-checkout-fields-for-brazil
