### ISSUE TITLE
Trocar Paypal por Cielo

### ISSUE THREAD

**Issue by thiagosjk** [thiagosjk/openPizza#21]
*nem um pouco urgente*
Ou manter as duas opções

**Comment by anywolf** [comment]
https://claudiosmweb.com/plugins/woocommerce-adicionar-cielo-como-metodo-de-pagamento/

**Comment by anywolf** [comment]
Configurar de acordo com que o Fernando quiser.

**Comment by anywolf** [comment]
Não fazer compra transparente.
