### ISSUE TITLE
Botão continuar comprando

### ISSUE THREAD

**Issue by thiagosjk** [thiagosjk/openPizza#22]
*critico*
Permitir com que, ao selecionar um pizza e clicar em comprar, o usuário tenha a opção de finalizar a compra ou de continuar comprando.

**Comment by anywolf** [comment]
Quando clico em comprar, ele adiciona no carrinho o que comprei e mostra o que estou comprando, um botão de ir para o carrinho e um de finalizar compra. O que eu não entendi é, porque ter um botão se ele continua na mesma página de comprar outras pizzas?

**Comment by anywolf** [comment]
Colocar botão apenas no carrinho de compra

**Comment by anywolf** [comment]
E se um usuário comprar de 2 pizzarias?
