### ISSUE TITLE
Opção repetir último pedido

### ISSUE THREAD

**Issue by thiagosjk** [thiagosjk/openPizza#26]
*critico*
Quando um usuário logar, permitir com que ele veja os últimos pedidos e repita um deles

**Comment by anywolf** [comment]
Quando o status do pedido estiver "completed" aparece para o usuário comprar de novo.

**Comment by anywolf** [comment]
para aparecer na tabela de compras feitas:
criar na linha 104 de wp-content/plugins/wedevs-dokan-plugin/templates/my-orders.php
$actions['repeat_order'] = array(
                                    'url'  => woocommerce_order_again_button($order),
                                );

**Comment by anywolf** [comment]
/wp-content/plugins/woocommerce/includes/shortcodes/class-wc-shortcode-my-account.php

**Comment by anywolf** [comment]
/wp-content/plugins/woocommerce/templates/myaccount.php

**Comment by anywolf** [comment]
Copiar o arquivo /wp-content/plugins/woocommerce/templates/myaccount
para wp-content/themes/openpizza-child/woocommerce/

com o mesmo nome "myaccount"

fazer as mudanças nesse arquivo

$actions['repeat_order'] = array(
'url' => woocommerce_order_again_button($order),
);

**Comment by anywolf** [comment]
Em  /wp-content/plugins/woocommerce/templates/myaccount
para wp-content/themes/openpizza-child/woocommerce/myaccount/my-orders
e wp-content/plugins/wedevs-dokan-plugin/templates/my-orders.php
colocar as seguintes linhas para não aparecer um botão vazio no template



foreach ( $actions as $key => $action ) {
										if ($action['name'] != '')
										echo '<a href="' . esc_url( $action['url'] ) . '" class="button ' . sanitize_html_class( $key ) . '">' . esc_html( $action['name'] ) . '</a>';
									}
