### ISSUE TITLE
Melhorar painel da pizzaria - Lista de pedidos

### ISSUE THREAD

**Issue by pandoapps** [thiagosjk/openPizza#40]
Tentar arrumar o layout para uma forma mais elegante (essa eu sei que será mais difícil :P )

**Comment by anywolf** [comment]
Favor informar o que deseja ser mudado.

**Comment by pandoapps** [comment]
As tabelas estão desalinhadas. O número de TD em cada TR está diferente.

Quando se pede Metade x Metade os dois sabores ficam bem distantes um do outro

A data do pedido não está formatada em dd/MM/yyyy hh:mm

Remover a palavra " → Limite de pedidos" do cabeçalho da tabela

os preços dos complementos estão aparecendo 2 vezes

Traduzir a palavra Print e Thermal printer
