### ISSUE TITLE
Accordion

### ISSUE THREAD

**Issue by anywolf** [thiagosjk/openPizza#8]
Quando clico a segunda vez no "monte sua pizza" no menu de compra vai para final da paǵina

**Comment by thiagosjk** [comment]
Ao atualizar o plugin "Accordion Shortcodes" perderemos o Hamburger Menu

**Comment by thiagosjk** [comment]
Adicionar a seguinte função no functions.php do tema para adicionar os novos parâmetros referentes ao accordeon

function accordion_fix(){
	$new_conf = array(
					array(
						"id"		=> "accordion-1",
						"autoClose" => true,
						"openFirst" => false,
						"openAll" => false,
						"clickToClose" => true,
						"scroll" => true,
	            	)
	            );
	wp_localize_script('accordion-shortcodes-script', 'accordionShortcodesSettings', $new_conf);

}
add_action('wp_footer', 'accordion_fix');
